### ISSUE TITLE
Session empty on creation

### ISSUE THREAD

**Issue by AndrewDonelson** [AndrewDonelson/next-appwrite-starter#2]
The session is empty. So after redirecting to account (profile) page no session. console shows something, but no session.

```sh
Submitted with FormData {
  '$ACTION_ID_34da0b0f339b64faae9cd17956855b7c6670dbdf': '',
  email: 'n*******d@gmail.com',
  password: '***********'
}
Signing in with nlaakald@gmail.com **********
Done! Session is {
  '$id': '665776d61c9073aae9ae',
  '$createdAt': '2024-05-29T18:41:26.131+00:00',
  '$updatedAt': '2024-05-29T18:41:26.131+00:00',
  userId: '6632b5ae003b1e166738',
  expire: '2025-05-29T18:41:26.117+00:00',
  provider: 'email',
  providerUid: 'n*******d@gmail.com',
  providerAccessToken: '',
  providerAccessTokenExpiry: '',
  providerRefreshToken: '',
  ip: '172.*.*.*',
  osCode: 'LIN',
  osName: 'GNU/Linux',
  osVersion: '',
  clientType: '',
  clientCode: '',
  clientName: '',
  clientVersion: '',
  clientEngine: '',
  clientEngineVersion: '',
  deviceName: 'desktop',
  deviceBrand: '',
  deviceModel: '',
  countryCode: 'us',
  countryName: 'United States',
  current: true,
  factors: [ 'password' ],
  secret: '',
  mfaUpdatedAt: ''
}
Cookie is {
  name: 'my-app-session',
  value: '',
  path: '/',
  httpOnly: true,
  sameSite: 'strict',
  secure: true
}
Getting logged in user...
Error getting logged in user Error: No session
    at createSessionClient (webpack-internal:///(rsc)/./lib/appwrite.ts:30:15)
    at getLoggedInUser (webpack-internal:///(rsc)/./lib/appwrite.ts:58:35)
    at Profile (webpack-internal:///(rsc)/./app/auth/profile/page.tsx:30:86)
    at e_ (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:264092)
    at e (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:268224)
    at eF (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:268712)
    at eq (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:274676)
    at ej (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:264920)
    at e_ (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:263962)
    at e (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:268224)
    at eF (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:268712)
    at /home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:265943
    at Array.toJSON (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:266407)
    at stringify (<anonymous>)
    at eq (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:274775)
    at eJ (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:275293)
    at AsyncLocalStorage.run (node:async_hooks:346:14)
    at Timeout._onTimeout (/home/andrew/Development/nextjs/next-appwrite-starter/node_modules/next/dist/compiled/next-server/app-page.runtime.dev.js:35:283288)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
Profile User is null
```

Console
```sh
BROWSER AND DEVICE    SESSION        LOCATION        IP    
on GNU/Linux                        United States   172.*.*.*
```

**Comment by AndrewDonelson** [comment]
Misconfigured APIKEY from .env
